@extends('layout')
@section('content')
<div id="table">
			<table class="ui table segment">
				<thead>
			    	<tr>
				    	<th>Name</th>
				    	<th>Lantai</th>
				    	<th>Kapasitas</th>
					    <th>Status</th>
					    <th>Waktu</th>
					    <th>Pesan</th>

			  		</tr>
				</thead>
			  	<tbody>
				    <tr>
				      	<td>John</td>
				      	<td>Approved</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				    </tr>
				    <tr>
				      	<td>John</td>
				      	<td>Approved</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				    </tr>
				    <tr>
				      	<td>John</td>
				      	<td>Approved</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				      	<td>None</td>
				    </tr>
			  	</tbody>
			</table>
</div>
@stop